version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: project_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medrec
      POSTGRES_USER: medrec
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network:
    driver: bridge